tissue: brain
group_reference: Relaxed
results_dir: results/brain
samples:
- id: E1
  donor_id: m_E1
  h5: data/Pool1/per_sample_outs/E1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/E1/sample_raw_feature_bc_matrix.tar.gz
  age: 3mo
  group: Early_Stress
  sex: F
  pool: Pool1
  library: Pool1
- id: E2
  donor_id: m_E2
  h5: data/Pool1/per_sample_outs/E2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/E2/sample_raw_feature_bc_matrix.tar.gz
  age: 3mo
  group: Early_Stress
  sex: F
  pool: Pool1
  library: Pool1
- id: MES1
  donor_id: m_MES1
  h5: data/Pool1/per_sample_outs/MES1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/MES1/sample_raw_feature_bc_matrix.tar.gz
  age: 3mo
  group: Early_Stress
  sex: M
  pool: Pool1
  library: Pool1
- id: MES2
  donor_id: m_MES2
  h5: data/Pool1/per_sample_outs/MES2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/MES2/sample_raw_feature_bc_matrix.tar.gz
  age: 3mo
  group: Early_Stress
  sex: M
  pool: Pool1
  library: Pool1
- id: L1_3mo
  donor_id: m_L1_3mo
  h5: data/Pool1/per_sample_outs/L1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/L1/sample_raw_feature_bc_matrix.tar.gz
  age: 3mo
  group: Late_Stress
  sex: F
  pool: Pool1
  library: Pool1
- id: L2_3mo
  donor_id: m_L2_3mo
  h5: data/Pool1/per_sample_outs/L2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/L2/sample_raw_feature_bc_matrix.tar.gz
  age: 3mo
  group: Late_Stress
  sex: F
  pool: Pool1
  library: Pool1
- id: MLS2
  donor_id: m_MLS2
  h5: data/Pool1/per_sample_outs/MLS2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/MLS2/sample_raw_feature_bc_matrix.tar.gz
  age: 3mo
  group: Late_Stress
  sex: M
  pool: Pool1
  library: Pool1
- id: MLS4
  donor_id: m_MLS4
  h5: data/Pool1/per_sample_outs/MLS4/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/MLS4/sample_raw_feature_bc_matrix.tar.gz
  age: 3mo
  group: Late_Stress
  sex: M
  pool: Pool1
  library: Pool1
- id: S1
  donor_id: m_S1
  h5: data/Pool1/per_sample_outs/S1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/S1/sample_raw_feature_bc_matrix.tar.gz
  age: 3mo
  group: Relaxed
  sex: F
  pool: Pool1
  library: Pool1
- id: S2
  donor_id: m_S2
  h5: data/Pool1/per_sample_outs/S2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/S2/sample_raw_feature_bc_matrix.tar.gz
  age: 3mo
  group: Relaxed
  sex: F
  pool: Pool1
  library: Pool1
- id: RelM1
  donor_id: m_RelM1
  h5: data/Pool1/per_sample_outs/RelM1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/RelM1/sample_raw_feature_bc_matrix.tar.gz
  age: 3mo
  group: Relaxed
  sex: M
  pool: Pool1
  library: Pool1
- id: RelM3
  donor_id: m_RelM3
  h5: data/Pool1/per_sample_outs/RelM3/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/RelM3/sample_raw_feature_bc_matrix.tar.gz
  age: 3mo
  group: Relaxed
  sex: M
  pool: Pool1
  library: Pool1
- id: E1-4WkF1
  donor_id: m_E1_4WkF1
  h5: data/Pool2/per_sample_outs/E1-4WkF1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/E1-4WkF1/sample_raw_feature_bc_matrix.tar.gz
  age: 4W
  group: Early_Stress
  sex: F
  pool: Pool2
  library: Pool2
- id: E2-4WkF2
  donor_id: m_E2_4WkF2
  h5: data/Pool2/per_sample_outs/E2-4WkF2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/E2-4WkF2/sample_raw_feature_bc_matrix.tar.gz
  age: 4W
  group: Early_Stress
  sex: F
  pool: Pool2
  library: Pool2
- id: E1-4WkM1
  donor_id: m_E1_4WkM1
  h5: data/Pool1/per_sample_outs/E1-4WkM1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/E1-4WkM1/sample_raw_feature_bc_matrix.tar.gz
  age: 4W
  group: Early_Stress
  sex: M
  pool: Pool1
  library: Pool1
- id: E2-4WkM2
  donor_id: m_E2_4WkM2
  h5: data/Pool1/per_sample_outs/E2-4WkM2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/E2-4WkM2/sample_raw_feature_bc_matrix.tar.gz
  age: 4W
  group: Early_Stress
  sex: M
  pool: Pool1
  library: Pool1
- id: L1-4WkF1
  donor_id: m_L1_4WkF1
  h5: data/Pool2/per_sample_outs/L1-4WkF1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/L1-4WkF1/sample_raw_feature_bc_matrix.tar.gz
  age: 4W
  group: Late_Stress
  sex: F
  pool: Pool2
  library: Pool2
- id: L2-4WkF2
  donor_id: m_L2_4WkF2
  h5: data/Pool2/per_sample_outs/L2-4WkF2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/L2-4WkF2/sample_raw_feature_bc_matrix.tar.gz
  age: 4W
  group: Late_Stress
  sex: F
  pool: Pool2
  library: Pool2
- id: L1-4WkM1
  donor_id: m_L1_4WkM1
  h5: data/Pool1/per_sample_outs/L1-4WkM1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/L1-4WkM1/sample_raw_feature_bc_matrix.tar.gz
  age: 4W
  group: Late_Stress
  sex: M
  pool: Pool1
  library: Pool1
- id: L2-4WkM2
  donor_id: m_L2_4WkM2
  h5: data/Pool2/per_sample_outs/L2-4WkM2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/L2-4WkM2/sample_raw_feature_bc_matrix.tar.gz
  age: 4W
  group: Late_Stress
  sex: M
  pool: Pool2
  library: Pool2
- id: S1-4WkF1
  donor_id: m_S1_4WkF1
  h5: data/Pool2/per_sample_outs/S1-4WkF1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/S1-4WkF1/sample_raw_feature_bc_matrix.tar.gz
  age: 4W
  group: Relaxed
  sex: F
  pool: Pool2
  library: Pool2
- id: S2-4WkF2
  donor_id: m_S2_4WkF2
  h5: data/Pool2/per_sample_outs/S2-4WkF2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/S2-4WkF2/sample_raw_feature_bc_matrix.tar.gz
  age: 4W
  group: Relaxed
  sex: F
  pool: Pool2
  library: Pool2
- id: S1-4WkM1
  donor_id: m_S1_4WkM1
  h5: data/Pool1/per_sample_outs/S1-4WkM1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool1/per_sample_outs/S1-4WkM1/sample_raw_feature_bc_matrix.tar.gz
  age: 4W
  group: Relaxed
  sex: M
  pool: Pool1
  library: Pool1
- id: S2-4WkM2
  donor_id: m_S2_4WkM2
  h5: data/Pool2/per_sample_outs/S2-4WkM2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/S2-4WkM2/sample_raw_feature_bc_matrix.tar.gz
  age: 4W
  group: Relaxed
  sex: M
  pool: Pool2
  library: Pool2
- id: E4
  donor_id: m_E4
  h5: data/Pool2/per_sample_outs/E4/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/E4/sample_raw_feature_bc_matrix.tar.gz
  age: P1
  group: Early_Stress
  sex: F
  pool: Pool2
  library: Pool2
- id: E7
  donor_id: m_E7
  h5: data/Pool2/per_sample_outs/E7/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/E7/sample_raw_feature_bc_matrix.tar.gz
  age: P1
  group: Early_Stress
  sex: F
  pool: Pool2
  library: Pool2
- id: E3
  donor_id: m_E3
  h5: data/Pool2/per_sample_outs/E3/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/E3/sample_raw_feature_bc_matrix.tar.gz
  age: P1
  group: Early_Stress
  sex: M
  pool: Pool2
  library: Pool2
- id: E6
  donor_id: m_E6
  h5: data/Pool2/per_sample_outs/E6/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/E6/sample_raw_feature_bc_matrix.tar.gz
  age: P1
  group: Early_Stress
  sex: M
  pool: Pool2
  library: Pool2
- id: L1_P1
  donor_id: m_L1_P1
  h5: data/Pool3/per_sample_outs/L1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool3/per_sample_outs/L1/sample_raw_feature_bc_matrix.tar.gz
  age: P1
  group: Late_Stress
  sex: M
  pool: Pool3
  library: Pool3
- id: L2_P1
  donor_id: m_L2_P1
  h5: data/Pool3/per_sample_outs/L2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool3/per_sample_outs/L2/sample_raw_feature_bc_matrix.tar.gz
  age: P1
  group: Late_Stress
  sex: M
  pool: Pool3
  library: Pool3
- id: C2
  donor_id: m_C2
  h5: data/Pool2/per_sample_outs/C2/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/C2/sample_raw_feature_bc_matrix.tar.gz
  age: P1
  group: Relaxed
  sex: F
  pool: Pool2
  library: Pool2
- id: C5
  donor_id: m_C5
  h5: data/Pool2/per_sample_outs/C5/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/C5/sample_raw_feature_bc_matrix.tar.gz
  age: P1
  group: Relaxed
  sex: F
  pool: Pool2
  library: Pool2
- id: C1
  donor_id: m_C1
  h5: data/Pool2/per_sample_outs/C1/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/C1/sample_raw_feature_bc_matrix.tar.gz
  age: P1
  group: Relaxed
  sex: M
  pool: Pool2
  library: Pool2
- id: C4
  donor_id: m_C4
  h5: data/Pool2/per_sample_outs/C4/sample_filtered_feature_bc_matrix.h5
  raw_h5: data/Pool2/per_sample_outs/C4/sample_raw_feature_bc_matrix.tar.gz
  age: P1
  group: Relaxed
  sex: M
  pool: Pool2
  library: Pool2
qc:
  pct_mt_max: 1.0
  pct_hemo_max: 5.0
  n_mads: 5
  min_counts: 500
  min_genes: 200
sex_markers:
  y_linked:
  - Ddx3y
  - Uty
  - Eif2s3y
  - Kdm5d
  x_linked:
  - Xist
random_seed: 42
annotation:
  celltypist_model: Developing_Mouse_Brains